repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0"
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@7.32.0
          - "eslint-config-oclif@^3.1"
          - "eslint-config-oclif-typescript@^1.0"
          - "eslint-plugin-node@^11.1.0"
