repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0"
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@7.32.0
          - "eslint-config-oclif@^4"
          - "eslint-config-oclif-typescript@^1"
          - "@typescript-eslint/eslint-plugin@^4"
          - "@typescript-eslint/parser@^4"
          - "eslint-config-xo-space@^0.29.0"
          - "eslint-plugin-mocha@^6.3.0"
          - "eslint-plugin-node@^11.1.0"
          - "eslint-plugin-unicorn@^19.0.1"
          - "typescript@^4.4"
