repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.0.0-beta.2" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@4.15.0
          - eslint-config-google@0.7.1
          - eslint-loader@1.6.1
          - eslint-plugin-react@6.10.3
          - babel-eslint@6.1.2
