on: [pull_request_target]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      - run: yarn --frozen
      - name: TypeScript Error Reporter
        uses: gozala/typescript-error-reporter-action@v1.0.7
      - run: yarn build
      - run: yarn test
