on:
  push:
  pull_request:
    types: [opened]
permissions:
  checks: write
  issues: write

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache: yarn
      - run: yarn --frozen
      - run: yarn build
      - run: yarn test
      - run: yarn pack
      - uses: actions/upload-artifact@v4
        with:
          name: vercel-openapi.tgz
          path: vercel-openapi-*.tgz
