on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update readme
jobs:
  update_readme:
    name: Update readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - run: yarn
      - name: Update readme
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            yarn run oclif-dev readme
          COMMIT_MESSAGE: "chore: update readme"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-update-readme-${PR_ID}"
          PR_TITLE: "chore: update readme"
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
